# Generated by Django 6.0 on 2026-01-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='faq_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='is_faq',
            field=models.BooleanField(default=False),
        ),
    ]
