# Generated by Django 6.0 on 2026-01-06 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_faq_order_question_is_faq'),
        ('users', '0010_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scraps',
            field=models.ManyToManyField(blank=True, related_name='scrapped_questions', to='users.profile'),
        ),
    ]
