# Generated by Django 6.0 on 2026-01-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_answer_id_alter_category_id_alter_question_id'),
        ('questions', '0003_question_faq_order_question_is_faq'),
    ]

    operations = [
    ]
