# Generated by Django 5.2.4 on 2026-01-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answer_author_alter_question_author_and_more'),
        ('questions', '0005_alter_answer_id_alter_category_id_alter_question_id'),
    ]

    operations = [
    ]
