# Generated by Django 6.0 on 2026-01-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secret_code',
            field=models.TextField(default='empty_code', max_length=20),
        ),
    ]
