# Generated by Django 6.0 on 2026-01-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_secret_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='secret_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='empty_code', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='empty_role', max_length=10),
        ),
    ]
