# Generated by Django 6.0 on 2026-01-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
