# Generated by Django 6.0 on 2026-01-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
