# Generated by Django 6.0 on 2026-01-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_alter_discussioncomment_id_alter_discussionpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussioncomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
